import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Home.module.scss';
import { Layout } from '../components/layout/main';
import { TryForFree } from '../components/cards/try-for-free/try-for-free';
import { ViktorCard } from '../components/cards/viktor/viktor';
import { StatProject } from '../components/cards/stat-project/stat-project';
import { HowToFind } from '../components/cards/fin-card/how-find';
import { CompagnieFinance } from '../components/cards/compagny-finance/compagny-finance';
import { ClientSpeak } from '../components/cards/client-speak/client-speak';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Landing Page By Claude MOTOBA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        
        <div className={styles.first_section}>
          <div className={styles.find_profesional}>
            <div className={styles.get_best}>
              <div className={styles.line_h4}></div>
              <h4>
                Get Best Accountant
              </h4>
              
            </div>
            <h1>
              Find Your Profesional Accountant Fast
            </h1>
            <p className={styles.paragraphe}>
              Next.js gives us CSS Modules by default, providing benefits like scoped styles and focused development in our app. How can we give our Next.js CSS superpowers with Sass?
            </p>

            <TryForFree/>

            <p className={styles.synced_contacts}>
              Synced contacts
            </p>

            
          </div>
          <div className={styles.section_picture}>
            <div className={styles.first_card_check}>
              
              <div className={styles.card_check}>
                c
              </div>
            </div>


            <ViktorCard/>
          </div>
        </div>
        <div className={styles.stat}>
          <StatProject/>
        </div>

        <div className={styles.find_best_accountant}>
          <h2>How to find the best accountants</h2>
          <p>The fast way to find your best accoutant</p>
          <div className={styles.container_how_find}>
            <HowToFind
              title = "Find Your Accountant"
              content = "Constructs an observable that, when subscribed, causes the configured DELETE request to execute on the server."
              url = "/favicon.ic"
            />
            <HowToFind
              title = "Make an appointment"
              content = "Constructs an observable that, when subscribed, causes the configured DELETE request to execute on the server."
              url = "/favicon.ic"
            />
            <HowToFind
              title = "Let's start working"
              content = "Constructs an observable that, when subscribed, causes the configured DELETE request to execute on the server."
              url = "/favicon."
            />
          </div>
        </div>

        <div className={styles.third_section}>
          <div className={styles.find_for_your_as}>
            <div className={styles.get_best}>
              <div className={styles.line_h4}></div>
              <h4>
                Get Best Accountant
              </h4>
              
            </div>
            <h2>
              Find job for you as Accountant
            </h2>
            <p>
              The safe and unsafe modifier keywords can be used in conjunction with all the rest of these keywords (although note browser support), and deal with helping you prevent aligning elements such that the content becomes inaccessible.
            </p>
            <div className={styles.footer_third_section}>
              <div className={styles.container_button}>
                <button>Upload CV</button>
              </div>
              <div className={styles.looking_link}>
                <Link href="#">
                  <a>looking for on employee ?</a>
                </Link>
              </div>
            </div>
          </div>

          <div className={styles.content_card_compagny}>
            <CompagnieFinance/>
          </div>

        </div>



        <div className={styles.four_section}>
            <div className={styles.container_profil}>
              <ViktorCard/>
            </div>

            <div className={styles.hire_your_as}>
              <div className={styles.get_best}>
                <div className={styles.line_h4}></div>
                <h4>
                  Get Best Accountant
                </h4>
                
              </div>
              <h2>
                Hire your Accountant and get contact
              </h2>
              <p>
                The safe and unsafe modifier keywords can be used in conjunction with all the rest of these keywords (although note browser support), and deal with helping you prevent aligning elements such that the content becomes inaccessible.
              </p>
              <div className={styles.footer_third_section}>
                <div className={styles.container_button}>
                  <button>Hire Employe</button>
                </div>
                <div className={styles.looking_link}>
                  <Link href="#">
                    <a>looking for a job ?</a>
                  </Link>
                </div>
              </div>
            </div>
        </div>

        <div className={styles.five_section}>

          <h2>
            Our Accountant and Client speak
          </h2>
          <p>The fast way to find your best accoutant</p>

          <div className={styles.container_three_card}>
            <ClientSpeak
              name="Claude Motoba"
              skill="Front-End Developer"
              title="Helping Your Business"
            />
            <ClientSpeak
              name="Jonas Fernando"
              skill="Fullstack Developer"
              title="Best service"
            />
            <ClientSpeak
              name="Michael Cooper"
              skill="UI UX Designer"
              title="Multilevel Impressed"
            />
          </div>
        </div>

      </Layout>

    </div>
  )
}
