import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.scss';
import { Layout } from '../components/layout/main';
import { TryForFree } from '../components/cards/try-for-free/try-for-free';
import { ViktorCard } from '../components/cards/viktor/viktor';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        
        <div className={styles.first_section}>
          <div className={styles.find_profesional}>
            <div className={styles.get_best}>
              <div className={styles.line_h4}></div>
              <h4>
                Get Best Accountant
              </h4>
              
            </div>
            <h1>
              Find Your Profesional Accountant Fast
            </h1>
            <p className={styles.paragraphe}>
              Next.js gives us CSS Modules by default, providing benefits like scoped styles and focused development in our app. How can we give our Next.js CSS superpowers with Sass?
            </p>

            <TryForFree/>

            <p className={styles.synced_contacts}>
              Synced contacts
            </p>

            
          </div>
          <div className={styles.section_picture}>
            <div className={styles.first_card_check}>
              
              <div className={styles.card_check}>
                c
              </div>
            </div>


            <ViktorCard/>
          </div>
        </div>

      </Layout>

    </div>
  )
}
